### ISSUE TITLE
Cannot enter local server with mod loaded (also update mod page)

### ISSUE THREAD

**Issue by Toilet-Man** [Fulmineo64/Guild#1]
**Modloader**
Fabric

**Describe the bug**
Installed guild-fabric-0.0.1.jar on both client and fabric server with other mods.
When I join it says this message:

`Connection Lost 
Registry remapping failed: Received ID map for minecraft:villager_profession contains IDs unknown to the receiver! - minecraft:guild_master`

**To Reproduce**
1. Launch Minecraft with Guild and other mods
2. Try to get in local server
3. See error

**Additional context**
Nothing else but **please** update [the mod page](https://modrinth.com/mod/guild) on Modrinth to allow people to send you issues about the mod more easily because people won't know how to find it as easily as I did

ADDITIONAL INFOS:

Just installed the mod v0.0.2 and it has the same problem (which is fine, I see that you're updating the mod with more features)

Anyway, here is the server log when I try to connect to my server:
[log.txt](https://github.com/Fulmineo64/Guild/files/7172759/log.txt)

**Comment by Fulmineo64** [comment]
Hi Toilet-Man,
thanks for being an early adopter of The Guild mod!

I've tried replicating this issue with no success, I've only experienced some other minor problems with the Guild Master's texture.

I think there's something I'm still missing about the configuration of the villager profession, that in the end could probably fix your problem too.

Something that could be interesting to try, if you can, is to see if creating a new server world with the mod pre-installed still yields the issue (that might explain why I'm not getting the error).
If you try make sure to not override your actual world in the process!

By the way, I just released the v0.0.3 that contains more bug fixes and features.

I'll keep you updated if I figure out something.

Thank you for your time and assistance.
Have a nice day!

**Comment by Toilet-Man** [comment]
> By the way, I just released the v0.0.3 that contains more bug fixes and features.

The issue was fixed after v0.0.3 thank you so much!!
