### ISSUE TITLE
full rus translate + mod menu 1.18 fabric GUILD mod

### ISSUE THREAD

**Issue by Shelbikk** [Fulmineo64/Guild#12]
[guild-fabric-0.3.5.zip](https://github.com/Fulmineo64/Guild/files/7708932/guild-fabric-0.3.5.zip)

I do not know how else to contact you.. pls upd

**Comment by Fulmineo64** [comment]
Hi Shelbikk,
thank you for your contribution.
I've updated the file in [v0.3.7](https://www.curseforge.com/minecraft/mc-mods/guild/files).

Have fun!
