### ISSUE TITLE
Inventory Sorting button present in GUI

### ISSUE THREAD

**Issue by onemorelevel0** [Fulmineo64/Guild#13]
**Modloader**
Did you experience the issue while playing on Fabric or on Forge?
Fabric

**Describe the bug**
The sorting button from [Inventory Sorting](https://www.curseforge.com/minecraft/mc-mods/inventory-sorting) is present in the GUI, right around the same position I assume it would be in a chest.

**To Reproduce**
1. Open GUI using hotkey.
2. Inventory Sorting button is present on the right side, down GUI in the middle.

**Expected behavior**
Sorter button to not be in the GUI for The Guild.

**Screenshots**
![2021-12-27_00 43 45](https://user-images.githubusercontent.com/76502039/147453535-884850d0-2bd0-421a-a199-218db858842c.png)

**Additional context**

**Comment by Fulmineo64** [comment]
Hi onemorelevel0,

I notified the author of the Inventory Sorter mod to make the required change, as it seems at a first glance that it isn't something I can fix within The Guild mod.

Keep an eye on the linked issue for updates on the matter.

**Comment by Fulmineo64** [comment]
Hi onemorelevel0,
kyrptonaught fixed this issue in no time.

Go thank him [here](https://github.com/kyrptonaught/Inventory-Sorter/issues/66) :)!
See ya!

**Comment by onemorelevel0** [comment]
Thank you for assigning it to him! Idk what I was thinking presenting the issue to you lol, but I really appreciate it
