### ISSUE TITLE
[Major Issue] crashing of server on click of finished quests

### ISSUE THREAD

**Issue by TheRealM18** [Fulmineo64/Guild#2]
**Modloader**
Fabric

**Describe the bug**
The issue is that I can crash server side on demand if I turn in all my quests super quickly, and crash the server, one after the last one. What I mean by that, is that if you turn all the quests in from top, and keep clicking super fast, it when you click on an empty one the server side will crash, not the client.

**To Reproduce**
1. Go to Single player
2. Click on accept all quests in a catigory
3. Spam turning
4. Crash server side.

**Expected behavior**
Not to crash the server, but ignore the empty slot.

**Screenshots**

**Additional context**
[latest.log](https://github.com/Fulmineo64/Guild/files/7178894/latest.log)

**Comment by Fulmineo64** [comment]
Hi TheRealM18,
thank you for opening the issue.

This problem should be fixed in the Alpha version v0.0.4.

I'm closing this for now, if you experience some other issues don't hesitate to open a new one!

Thank you again.
Have a nice day!
