### ISSUE TITLE
Crash client Fabric 1.17.1

### ISSUE THREAD

**Issue by Anhelm** [Fulmineo64/Guild#4]
**Modloader**
Fabric 1.17.1
**Describe the bug**
When trying to talk to the Guild Master, the client fails

**To Reproduce**
1. I find the Guild Master
2. I click on it with the right mouse button
3. A crash occurs
[crash-2021-09-20_10.29.24-client.txt](https://github.com/Fulmineo64/Guild/files/7193501/crash-2021-09-20_10.29.24-client.txt)

**Comment by Fulmineo64** [comment]
Hello Anhelm.
I've added some extra checks to avoid that crash.
There's the possibility that the Guild Master is selling an invalid profession licence (damn those villagers!).
The changes on version 0.0.6 should fix your problem, so I'm closing the issue for now.
If even with the v0.0.6 you still experience the problem please open a new issue with the updated error log.
Thank you!
