### ISSUE TITLE
Crash when accessing guildmaster  on server

### ISSUE THREAD

**Issue by TheRanker** [Fulmineo64/Guild#8]
**Modloader**
Did you experience the issue while playing on Fabric or on Forge?
Fabric 
**Describe the bug**
https://bytebin.lucko.me/Z5GoGpeUUR
**To Reproduce**
1. Go to '...'. Guild master
2. Click on '....' him
3. Scroll down to '....' crash to desktop 

**Expected behavior**
No crash
**Screenshots**

**Additional context**

**Comment by Anhelm** [comment]
This error has been fixed in version 0.0.7
You are using version 0.0.5

**Comment by Fulmineo64** [comment]
Hi TheRanker,
as Anhelm said, could you please update to the latest version and try again?
Thank you.

**Comment by Fulmineo64** [comment]
Hi TheRanker.
I'm closing this for now.

If the problem is still present in the latest releases please open another issue.
Thank you!
