### ISSUE TITLE
[Suggestion] Accessing GUI through a block

### ISSUE THREAD

**Issue by Estrelaura** [Fulmineo64/Guild#9]
I think a option to only acess the quest GUI through the guild master table could be interesting. It's nice to have the feeling of delivering the quest to someone.

**Comment by Fulmineo64** [comment]
Hi Estrelaura,
cool concept but there are some problems with it.

You can borrow or craft a Guild Master table and place it wherever you want so it's a bit too easy to defeat this mechanism (also I have other use planned for it 😉).

Instead I propose to you this, you have to be max X blocks (configurable) away from a Guild Master to complete the quests.

I've already added this last version to my TODO list for after the v1.0.0 release.
So, if it will still makes sense at that point, i'll probably add it.

You're welcome to join my Discord to share and discuss more ideas:
https://discord.com/invite/G8s2q4wMnt

See ya!
